### ISSUE TITLE
Uploading a `datapackage.json` with bad JSON returns a server error

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-datapackager#37] opened 2016-01-08 11:00 UTC
For instance   

 ``` 
    {   
        "title": "Test no url"
        "name": "bond-yields-uk-10y",
        "resources": [
            {
                "format": "csv",
                "path": "data/quarterly.csv"
            }
        ],
    }   
 ``` 

Trace:

    ``` 
    File '/home/adria/dev/pyenvs/ckan_plain/src/ckanext-datapackager/ckanext/datapackager/logic/action/create.py', line 69 in _load_and_validate_datapackage
      dp = datapackage.DataPackage(upload.file)
    File '/home/adria/dev/pyenvs/ckan_plain/src/datapackage/datapackage/datapackage.py', line 56 in __init__
      self._metadata = self._load_metadata(metadata)
    File '/home/adria/dev/pyenvs/ckan_plain/src/datapackage/datapackage/datapackage.py', line 290 in _load_metadata
      the_metadata = json.load(the_metadata)
    File '/usr/lib/python2.7/json/__init__.py', line 290 in load
      **kw)
    File '/usr/lib/python2.7/json/__init__.py', line 338 in loads
      return _default_decoder.decode(s)
    File '/usr/lib/python2.7/json/decoder.py', line 366 in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File '/usr/lib/python2.7/json/decoder.py', line 382 in raw_decode
      obj, end = self.scan_once(s, idx)
    ValueError: Expecting , delimiter: line 3 column 5 (char 33)
    ```

**Comment by vitorbaptista** [comment] 2016-01-13 17:16
Fixed on https://github.com/okfn/datapackage-py/commit/23ff2c1b4cd24489a9b3eab446df992b210ac48c and https://github.com/okfn/datapackage-py/commit/329c1e152c9a1645e4d224f9f31a8587d8fb5d72

![Error message on invalid JSON file](https://cloud.githubusercontent.com/assets/76945/12301495/4127d7ba-ba18-11e5-9db8-725efa7bd4d0.png)

The error message can be improved, though. The current error message is useful when debugging the JSON, but the message is a bit cryptic in the sense that the issue is with the JSON. Maybe simply saying "Unable to load JSON" might be more useful. What do you think, @amercader?

**Comment by vitorbaptista** [comment] 2016-02-03 19:08
I'm closing this issue as I think the solution is good enough. The exceptions messages come from DataPackage, as well, so any improvements done on https://github.com/okfn/datapackage-py/issues/27 will reflect here :+1:

**Closed by vitorbaptista** 2016-02-03 19:08 UTC
Labels: bug
