### ISSUE TITLE
Uploading a `datapackage.json` with no `url` in the resource returns confusing error

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-datapackager#38] opened 2016-01-08 11:03 UTC
For instance:

```
{
    "title": "Test no url"
    "name": "bond-yields-uk-10y",
    "resources": [
        {
            "format": "csv",
            "path": "data/quarterly.csv"
        }
    ]
}
```

You get a validation error about the URL being missing, but it's not clear what URL are we talking about.
Moreover CKAN displays an error message in the Upload/Link field making it extra confusing as it implies that there is something wrong with the upload.

![error](http://i.imgur.com/HsjCquU.png)

I understand that this is caused by the standard CKAN validation and the Data Package conversion librart but maybe we should capture the error at the extension level.

And definitely provide more guidance as to what the `datapackage.json` should have for a successful import.

**Comment by amercader** [comment] 2016-01-08 11:34
It's even worse when using the API, as it definitely seems to contradict what you just sent:

```
curl -X POST http://localhost:5001/api/action/package_create_from_datapackage -H 'Authorization: 3869cb71-96da-46f1-b5a9-767ca73af73f' -d '{"url": "https://raw.githubusercontent.com/amercader/car-fuel-and-emissions/master/datapackage.json"}'


{"help": "http://localhost:5001/api/3/action/help_show?name=package_create_from_datapackage", "success": false, "error": {"url": ["Missing value"], "__type": "Validation Error"}
```

**Comment by vitorbaptista** [comment] 2016-01-13 16:49
The main problem here is that the datapackage is being uploaded outside a ZIP file, and its resource contains only a local path. To avoid a resource with a path like `/etc/shadow`, this extension only accepts paths relative to the datapackage's ZIP file. As you haven't uploaded a ZIP, but the actual datapackage.json, that doesn't exist, so no local path is valid.

The extension ends up trying to create a CKAN resource with only `"format": "csv"` as attributes. As CKAN itself requires that resources have an URL, that raises an exception, which is what you see.

There're a few ways of fixing this. We could either ignore any resources that weren't able to be created on CKAN when importing a datapackage (probably showing a warning to the user). In this example, the user will end up with a dataset without resources. Actually, this is what happens right now, but as the user isn't redirected to the newly created dataset, it doesn't seems so (we should import the datapackage inside a transaction to avoid this).

The other way is to improve the error message.

**Comment by vitorbaptista** [comment] 2016-01-14 00:00
FYI, this issue will only happen if the sample `datapackage.json` is inside a ZIP, as it isn't a safe datapackage otherwise (for what's safe, check https://github.com/okfn/datapackage-py/blob/master/datapackage/datapackage.py#L131).

It also throws another error: it fails because it can't open the "data/quarterly.csv" file, which is closer to what we want. I'm working on it.

**Comment by vitorbaptista** [comment] 2016-01-14 14:39
Related to https://github.com/ckan/ckanext-datapackager/issues/41

**Comment by vitorbaptista** [comment] 2016-02-03 19:07
Uploading the `datapackage.json` @amercader pasted in the first issue as a JSON fails because it's an unsafe datapackage (check https://github.com/okfn/datapackage-py/issues/24). If we ZIP that and post it it fails with:

> Datapackage: Couldn't create some of the resources. Please make sure that all resources' files are accessible.

That seems good enough for me, so I'm closing this. Feel free to reopen it if needed :+1:

**Closed by vitorbaptista** 2016-02-03 19:07 UTC

**Comment by ndkv** [comment] 2016-03-22 08:18
I ran into a similar safe/unsafe issue: uploading a remote `datapackage.json` (i.e. unzipped) that uses relative `path`s for its resources [1] gives an `Unsafe ...` error while uploading the same package with "absolute" `url`s [2] works fine. 

This seems to be the intended behaviour

> To avoid a resource with a path like `/etc/shadow`, this extension only accepts paths relative to the datapackage's ZIP file. As you haven't uploaded a ZIP, but the actual datapackage.json, that doesn't exist, so no local path is valid.

While I see the need to prevent `/etc/shadow`-like paths, I'm not sure disallowing relative resource `path`s for remote packages (i.e. unzipped) is intended as well. Also, the spec allows relative `path`s for remote pacakges

> NOTE: the use of a `url` allows a data package to reference data not contained locally in the Data Package. _The `path` attribute may also be used for Data Packages located online – in this case it determines the resource file’s URL relative to the `datapackage.json`’s URL._

I'm not familiar (at all) with inner working of CKAN/extension code but it seems that the culprit is line 151 in the `safe` function linked above

````python
if not resource.local_data_path.startswith(self.base_path):
````
I guess remote data packages have their URL as `base_path`. Relative `path`s are rejected since they don't start with the URL. `url`s on the other hand pass this test just fine. 

So, to allow relative paths on remote packages we'd need to treat `path` differently, right? 

[1] https://github.com/ndkv/datasets/blob/master/gemeenschappelijke_regelingen/partial/datapackage.json
[2] https://github.com/ndkv/datasets/blob/gh-pages/gemeenschappelijke_regelingen/partial/datapackage.json
[3] http://dataprotocols.org/data-packages/#required-fields-1

BTW The "unsafe" message initially tricked me into thinking that the package's `description` attribute was the culprit as it contains links (it isn't and the links are stripped). It might be better, if possible, to mention something about the difference between `url` and `path`.

**Comment by amercader** [comment] 2016-03-22 09:37
Thanks for the heads up @ndkv. @vitorbaptista what do you think?

**Comment by vitorbaptista** [comment] 2016-03-22 10:09
I created an issue to track it at https://github.com/frictionlessdata/datapackage-py/issues/63, as this is a bug in `datapackage-py`. Thanks for the report, @ndkv.

I agree that this is a bug and should be fixed. I won't have time to do it for now, unfortunately. @ndkv, you already know where the bug lies. If you have some time, please go ahead and send a pull request. The code is well tested and relatively straight-forward, so you shouldn't have issues :wink: I'm at https://gitter.im/frictionlessdata/chat as well and I'd be happy to help.

**Comment by ndkv** [comment] 2016-03-23 11:23
Thanks for the quick reply! 

I'll start working on a fix. :)
